# Generated by Django 4.0.4 on 2022-05-12 01:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_tema', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Pergunta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pergunta', models.CharField(max_length=100)),
                ('resposta', models.IntegerField()),
                ('prim_res', models.CharField(max_length=100)),
                ('sec_res', models.CharField(max_length=100)),
                ('ter_res', models.CharField(max_length=100)),
                ('quar_res', models.CharField(blank=True, max_length=100)),
                ('quin_res', models.CharField(blank=True, max_length=100)),
                ('tema', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teste.tema')),
            ],
        ),
    ]
