# Generated by Django 4.0.4 on 2022-05-12 20:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teste', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Tema',
            new_name='Temas',
        ),
    ]
