# Generated by Django 4.0.4 on 2022-05-12 22:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teste', '0002_rename_tema_temas'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Temas',
            new_name='Tema',
        ),
    ]
